# Generated by Django 2.2.6 on 2019-11-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
