# Generated by Django 2.2.6 on 2019-11-06 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20191106_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
