# Generated by Django 2.2.6 on 2019-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_loanapplication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
