# Generated by Django 2.2.6 on 2019-11-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmaster',
            name='cust_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
