# Generated by Django 2.2.6 on 2019-11-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_loanmaster_cust_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanmaster',
            old_name='c_id',
            new_name='cust',
        ),
    ]
