# Generated by Django 2.2.6 on 2019-11-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191109_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('interest_amount', models.FloatField()),
                ('emi_amount', models.FloatField()),
            ],
        ),
    ]
