# Generated by Django 2.2.6 on 2019-11-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191109_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanmaster',
            old_name='app_id',
            new_name='app',
        ),
    ]
