# Generated by Django 2.2.6 on 2019-11-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191109_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='loan_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.LoanMaster'),
            preserve_default=False,
        ),
    ]
