# Generated by Django 2.2.6 on 2019-11-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_emi_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emi',
            old_name='loan_id',
            new_name='loan',
        ),
    ]
