# Generated by Django 2.2.6 on 2019-11-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='c_id',
            new_name='cust',
        ),
    ]
