# Generated by Django 2.2.6 on 2019-11-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20191128_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='loan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.LoanMaster'),
            preserve_default=False,
        ),
    ]
